[package]
name = "lighter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = { version = "2.21.0", features = ["xlib", "xrandr"] }
packed_struct = "0.10"

[build-dependencies]
cc = "1.0"